export default {
    'stat.leaveGame': 'Games quit',
    'stat.playOneMinute': 'Minutes Played',
    'stat.timeSinceDeath': 'Since Last Death',
    'stat.sneakTime': 'Sneak Time',
    'stat.walkOneCm': 'Distance Walked',
    'stat.crouchOneCm': 'Distance Crouched',
    'stat.sprintOneCm': 'Distance Sprinted',
    'stat.swimOneCm': 'Distance Swum',
    'stat.fallOneCm': 'Distance Fallen',
    'stat.climbOneCm': 'Distance Climbed',
    'stat.flyOneCm': 'Distance Flown',
    'stat.diveOneCm': 'Distance Dove',
    'stat.minecartOneCm': 'Distance by Minecart',
    'stat.boatOneCm': 'Distance by Boat',
    'stat.pigOneCm': 'Distance by Pig',
    'stat.horseOneCm': 'Distance by Horse',
    'stat.aviateOneCm': 'Distance by Elytra',
    'stat.jump': 'Jumps',
    'stat.damageDealt': 'Damage Dealt',
    'stat.damageTaken': 'Damage Taken',
    'stat.deaths': 'Number of Deaths',
    'stat.mobKills': 'Mob Kills',
    'stat.playerKills': 'Player Kills',
    'stat.killEntity.Enderman': 'Endermen Slain',
    'stat.entityKilledBy.Enderman': 'Slain by Enderman',
    'stat.drop': 'Items Dropped',
    'stat.itemEnchanted': 'Items Enchanted',
    'stat.animalsBred': 'Animals Bred',
    'stat.fishCaught': 'Fish Caught',
    'stat.talkedToVillager': 'Talked to Villagers',
    'stat.tradedWithVillager': 'Traded with Villagers',
    'stat.cakeSlicesEaten': 'Cake Slices Eaten',
    'stat.cauldronFilled': 'Caludrons Filled',
    'stat.cauldronUsed': 'Water Taken from Cauldron',
    'stat.armorCleaned': 'Armor Pieces Cleaned',
    'stat.bannerCleaned': 'Banners Cleaned',
    'stat.brewingstandInteraction': 'Interactions with Brewing Stand',
    'stat.beaconInteraction': 'Interactions with Beacon',
    'stat.craftingTableInteraction': 'Interactions with Crafting Table',
    'stat.furnaceInteraction': 'Interactions with Furnace',
    'stat.dispenserInspected': 'Dispensers Searched',
    'stat.dropperInspected': 'Droppers Searched',
    'stat.hopperInspected': 'Hoppers Searched',
    'stat.chestOpened': 'Chests Opened',
    'stat.trappedChestTriggered': 'Trapped Chests Triggered',
    'stat.enderchestOpened': 'Ender Chests Opened',
    'stat.noteblockPlayed': 'Noteblocks played',
    'stat.noteblockTuned': 'Noteblocks tuned',
    'stat.flowerPotted': 'Plants potted',
    'stat.recordPlayed': 'Records Played',
    'stat.sleepInBed': 'Times Slept in a Bed',
    'stat.shulkerBoxOpened': 'Shulker Boxes Opened',
};
